{
 "title": "Cashflow Summary",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Revenue'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Revenue'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Expenses'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Expenses'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Cost Of Revenue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Cost of Revenue'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Cost of Revenue'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Other Income",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Other Income'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Other Income'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Other Expenses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Other Expenses'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Other Expenses'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Sorted Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    (\n        -- Revenue\n        SUM(CASE WHEN gh.top_category = 'Revenue'         THEN t.value_usd ELSE 0 END)\n        -- Cost of Revenue\n      - SUM(CASE WHEN gh.top_category = 'Cost of Revenue' THEN t.value_usd ELSE 0 END)\n        -- Expenses\n      - SUM(CASE WHEN gh.top_category = 'Expenses'        THEN t.value_usd ELSE 0 END)\n        -- Other Income\n      + SUM(CASE WHEN gh.top_category = 'Other Income'    THEN t.value_usd ELSE 0 END)\n        -- Other Expenses\n      - SUM(CASE WHEN gh.top_category = 'Other Expenses'  THEN t.value_usd ELSE 0 END)\n    ) AS total_net\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    (\n        -- Revenue\n        SUM(CASE WHEN gh.top_category = 'Revenue'         THEN t.value_usd ELSE 0 END)\n        -- Cost of Revenue\n      - SUM(CASE WHEN gh.top_category = 'Cost of Revenue' THEN t.value_usd ELSE 0 END)\n        -- Expenses\n      - SUM(CASE WHEN gh.top_category = 'Expenses'        THEN t.value_usd ELSE 0 END)\n        -- Other Income\n      + SUM(CASE WHEN gh.top_category = 'Other Income'    THEN t.value_usd ELSE 0 END)\n        -- Other Expenses\n      - SUM(CASE WHEN gh.top_category = 'Other Expenses'  THEN t.value_usd ELSE 0 END)\n    ) AS total_net\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Weekly Cashflow",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 4 },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n        ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    t.timestamp,\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income')         THEN t.value_usd ELSE 0 END) AS \"Total Revenue\",\n    SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses')  THEN t.value_usd ELSE 0 END) * -1 AS \"Total Expenses\",\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income') THEN t.value_usd ELSE 0 END) - SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses')  THEN t.value_usd ELSE 0 END) AS \"Net\"\nFROM treasury_txs AS t\nJOIN group_hierarchy gh\n    ON t.txgroup_id = gh.txgroup_id\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\nGROUP BY timestamp\nORDER BY timestamp;",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n        ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    t.timestamp,\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income')         THEN t.value_usd ELSE 0 END) AS \"Total Revenue\",\n    SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses')  THEN t.value_usd ELSE 0 END) * -1 AS \"Total Expenses\",\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income') THEN t.value_usd ELSE 0 END) - SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses')  THEN t.value_usd ELSE 0 END) AS \"Net\"\nFROM treasury_txs AS t\nJOIN group_hierarchy gh\n    ON t.txgroup_id = gh.txgroup_id\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\nGROUP BY timestamp\nORDER BY timestamp;",
     "timeColumns": [ "timestamp" ]
    }
   ]
  },
  {
   "title": "Unsorted (Inbound)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Sort Me (Inbound)'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Sort Me (Inbound)'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unsorted (Outbound)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Sort Me (Outbound)'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT txgroup_id, name AS top_category, parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    SUM(t.value_usd) AS total_revenue\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE gh.top_category = 'Sort Me (Outbound)'\n  AND t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    (\n        -- Revenue\n        SUM(CASE WHEN gh.top_category = 'Revenue'         THEN t.value_usd ELSE 0 END)\n        -- Cost of Revenue\n      - SUM(CASE WHEN gh.top_category = 'Cost of Revenue' THEN t.value_usd ELSE 0 END)\n        -- Expenses\n      - SUM(CASE WHEN gh.top_category = 'Expenses'        THEN t.value_usd ELSE 0 END)\n        -- Other Income\n      + SUM(CASE WHEN gh.top_category = 'Other Income'    THEN t.value_usd ELSE 0 END)\n        -- Other Expenses\n      - SUM(CASE WHEN gh.top_category = 'Other Expenses'  THEN t.value_usd ELSE 0 END)\n        -- Sort Me (Inbound)\n      + SUM(CASE WHEN gh.top_category = 'Sort Me (Inbound)'    THEN t.value_usd ELSE 0 END)\n        -- Sort Me (Outbound)\n      - SUM(CASE WHEN gh.top_category = 'Sort Me (Outbound)'    THEN t.value_usd ELSE 0 END)\n    ) AS total_net\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n      ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    (\n        -- Revenue\n        SUM(CASE WHEN gh.top_category = 'Revenue'         THEN t.value_usd ELSE 0 END)\n        -- Cost of Revenue\n      - SUM(CASE WHEN gh.top_category = 'Cost of Revenue' THEN t.value_usd ELSE 0 END)\n        -- Expenses\n      - SUM(CASE WHEN gh.top_category = 'Expenses'        THEN t.value_usd ELSE 0 END)\n        -- Other Income\n      + SUM(CASE WHEN gh.top_category = 'Other Income'    THEN t.value_usd ELSE 0 END)\n        -- Other Expenses\n      - SUM(CASE WHEN gh.top_category = 'Other Expenses'  THEN t.value_usd ELSE 0 END)\n        -- Sort Me (Inbound)\n      + SUM(CASE WHEN gh.top_category = 'Sort Me (Inbound)'    THEN t.value_usd ELSE 0 END)\n        -- Sort Me (Outbound)\n      - SUM(CASE WHEN gh.top_category = 'Sort Me (Outbound)'    THEN t.value_usd ELSE 0 END)\n    ) AS total_net\nFROM treasury_txs t\nJOIN group_hierarchy gh USING (txgroup_id)\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Weekly Cashflow (incl. Unsorted)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n        ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    t.timestamp,\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income','Sort Me (Inbound)')         THEN t.value_usd ELSE 0 END) AS \"Total Revenue (incl. Unsorted)\",\n    SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses','Sort Me (Outbound)')  THEN t.value_usd ELSE 0 END) * -1 AS \"Total Expenses (incl. Unsorted)\",\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income','Sort Me (Inbound)') THEN t.value_usd ELSE 0 END) - SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses','Sort Me (Outbound)')  THEN t.value_usd ELSE 0 END) AS \"Net (incl. Unsorted)\"\nFROM treasury_txs AS t\nJOIN group_hierarchy gh\n    ON t.txgroup_id = gh.txgroup_id\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\nGROUP BY timestamp\nORDER BY timestamp;",
     "rawQueryText": "WITH RECURSIVE group_hierarchy (txgroup_id, top_category, parent_txgroup) AS (\n    SELECT\n        txgroup_id,\n        name AS top_category,\n        parent_txgroup\n    FROM txgroups\n    WHERE parent_txgroup IS NULL\n\n    UNION ALL\n\n    SELECT\n        child.txgroup_id,\n        parent.top_category,\n        child.parent_txgroup\n    FROM txgroups AS child\n    JOIN group_hierarchy AS parent\n        ON child.parent_txgroup = parent.txgroup_id\n)\nSELECT\n    t.timestamp,\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income','Sort Me (Inbound)')         THEN t.value_usd ELSE 0 END) AS \"Total Revenue (incl. Unsorted)\",\n    SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses','Sort Me (Outbound)')  THEN t.value_usd ELSE 0 END) * -1 AS \"Total Expenses (incl. Unsorted)\",\n    SUM(CASE WHEN gh.top_category in ('Revenue', 'Other Income','Sort Me (Inbound)') THEN t.value_usd ELSE 0 END) - SUM(CASE WHEN gh.top_category in ('Cost of Revenue','Expenses','Other Expenses','Sort Me (Outbound)')  THEN t.value_usd ELSE 0 END) AS \"Net (incl. Unsorted)\"\nFROM treasury_txs AS t\nJOIN group_hierarchy gh\n    ON t.txgroup_id = gh.txgroup_id\nWHERE t.timestamp >= $__from/1000\n  AND t.timestamp <= $__to/1000\nGROUP BY timestamp\nORDER BY timestamp;",
     "timeColumns": [ "timestamp" ]
    }
   ]
  }
 ]
}