# Generated by Django 3.2.14 on 2024-03-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_merge_0027_auto_20240312_1142_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='computer_quantity_use_max',
            field=models.IntegerField(verbose_name='computer quantity use max', default=10, null=True),
        ),
       
    ]
