TOOL_REQUIRED = {
    "player": "sword",
    "sapling": "shovel",
    "treeling": "axe",
    "tree": "axe",
    "wood": "axe",
    "spore": "shovel",
    "mushroom": "axe",
    "flint": "pickaxe",
    "ice": "pickaxe",
    "stick": "axe",
    "campfire": "axe",
    "carroot": "shovel",
    "carrot": "shovel",
    "rock": "pickaxe",
    "big rock": "pickaxe",
    "clay": "shovel",
    "stone": "pickaxe",
    "stone brick": "pickaxe",
    "brick": "pickaxe",
    "rabbit child": "sword",
    "rabbit adult": "sword",
    "sawbench": "axe",
    "wood pulp": "shovel",
    "manual press": "pickaxe",
    "bluebell": "shovel",
    "small crate": "axe",
    "mushroom block": "axe",
    "mushroom shaper": "axe",
    "dirt": "shovel",
    "coal ore": "pickaxe",
    "coal": "pickaxe",
    "composter": "axe",
    "bonsai pot": "axe",
    "sand": "shovel",
}
TOOL_EFFICIENCY = {
    "flint": 1, 
    "rock": 2
}