# Generated by Django 3.2.14 on 2023-07-21 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tutorial_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=False, verbose_name='created at')),
                ('order', models.TextField(verbose_name='order'))
            ],
        ),
        migrations.CreateModel(
            name='tutorial_sub_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=False, verbose_name='created at')),
               
                ('group_id', models.IntegerField(verbose_name='group_id'))
            ],
        ),
        migrations.CreateModel(
            name='tutorial_section_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=False, verbose_name='created at')),
                ('url', models.TextField(verbose_name='url')),
                ('sub_group_id', models.IntegerField(verbose_name='sub_group_id'))
            ],
        ),
        migrations.CreateModel(
            name='tutorial_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=False, verbose_name='created at')),
                ('section_id', models.IntegerField(verbose_name='section_id')),
                ('content', models.TextField(verbose_name='content'))
            ],
        ),
    ]
