# Generated by Django 3.2.14 on 2024-03-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='TutorialContent',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('title', models.TextField(default='')),
        #         ('content', models.TextField(null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
        #         ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
        #     ],
        #     options={
        #         'db_table': 'tutorial_content',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='TutorialGroup',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('order', models.IntegerField(default=0, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
        #         ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
        #     ],
        #     options={
        #         'db_table': 'tutorial_group',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='TutorialSectionContent',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('title', models.TextField(default='')),
        #         ('url', models.TextField(default='')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
        #         ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
        #     ],
        #     options={
        #         'db_table': 'tutorial_section_content',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='TutorialSubGroup',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
        #         ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
        #         ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='tutorials.tutorialgroup')),
        #     ],
        #     options={
        #         'db_table': 'tutorial_sub_group',
        #     },
        # ),
        # migrations.DeleteModel(
        #     name='tutorial_content',
        # ),
        # migrations.DeleteModel(
        #     name='tutorial_group',
        # ),
        # migrations.DeleteModel(
        #     name='tutorial_section_content',
        # ),
        # migrations.DeleteModel(
        #     name='tutorial_sub_group',
        # ),
        # migrations.AddField(
        #     model_name='tutorialsectioncontent',
        #     name='sub_group_id',
        #     field=models.ForeignKey(db_column='sub_group_id', on_delete=django.db.models.deletion.CASCADE, related_name='section_contents', to='tutorials.tutorialsubgroup'),
        # ),
        # migrations.AddField(
        #     model_name='tutorialcontent',
        #     name='section_id',
        #     field=models.OneToOneField(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_content', to='tutorials.tutorialsectioncontent'),
        # ),
    ]
