# Generated by Django 3.2.14 on 2023-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_project_need_to_qc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='need_to_qa',
            field=models.BooleanField(default=False, help_text='Whether or not the project is needed to review tasks', verbose_name='turn QA/QC function on/off'),
        ),
        migrations.AlterField(
            model_name='project',
            name='need_to_qc',
            field=models.BooleanField(default=False, help_text='Whether or not the project is needed to QC tasks', verbose_name='enable QC step after QA'),
        ),
    ]
