# Generated by Django 3.2.14 on 2024-03-26 03:26

from django.db import migrations, models
from ..models import Project
from django.utils.translation import gettext_lazy as _

class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_project_predict_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="predict_config",
            field=models.JSONField(
                _("predict config"),
                default=None,
                blank=True,
                null=True,
                help_text=_("Store predict config"),
            ),
        ),
    ]
