# Generated by Django 3.2.14 on 2024-27-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute_marketplace', '0029_auto_20240424_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name="computegpu",
            name="gpu_tflops",
            field=models.TextField(('gpu_tflops'), blank=True, null=True),
        ),
    ]
