# Generated by Django 3.2.14 on 2024-27-03 15:08

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _
from ..models import ComputeGPU


class Migration(migrations.Migration):

    dependencies = [
        ("compute_marketplace", "0042_add_field_computegpu"),
    ]

    operations = [
        migrations.AddField(
            model_name="computegpu",
            name="cores",
            field=models.TextField(_("cores"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="cuda_cores",
            field=models.TextField(_("cuda_cores"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="memory_bus_width",
            field=models.TextField(_("memory_bus_width"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="gpu_clock_mhz",
            field=models.TextField(_("gpu_clock_mhz"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="mem_clock_mhz",
            field=models.TextField(_("mem_clock_mhz"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="disk",
            field=models.TextField(_("disk"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="disk_used",
            field=models.TextField(_("disk_used"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="disk_free",
            field=models.TextField(_("disk_free"), blank=True, null=True),
        ),
    ]
