from .object import OWLObject
from .entity import OWLEntity
from .data_range import OWLDataRange
from .axiom import OWLAxiom
from .annotation_axiom import OWLAnnotationAxiom
from .annotation_value import OWLAnnotationValue
from .assertion import OWLAssertion
from .class_axiom import OWLClassAxiom
from .class_expression import OWLClassExpression
from .individual import OWLIndividual
from .data_property_axiom import OWLDataPropertyAxiom
from .object_property_axiom import OWLObjectPropertyAxiom
from .property_range import OWLPropertyRange
from .annotation_subject import OWLAnnotationSubject
from .data_property_expression import OWLDataPropertyExpression
from .object_property_expression import OWLObjectPropertyExpression