# Generated by Django 3.2.14 on 2024-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogModelMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated at')),
                ('catalog_id', models.IntegerField(verbose_name='catalog id')),
                ('order', models.IntegerField(verbose_name='order')),
                ('tag', models.TextField(verbose_name='tag')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_marketplace', 'In Marketplace'), ('rented_bought', 'Rented/Bought'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend'), ('expired', 'Expired')], default='created', max_length=64, null=True, verbose_name='status')),
                ('file', models.FileField(null=True, upload_to='export')),
            ],
        ),
        migrations.CreateModel(
            name='CheckpointModelMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated at')),
                ('owner_id', models.IntegerField(verbose_name='owner id')),
                ('author_id', models.IntegerField(verbose_name='author id')),
                ('checkpoint_storage_id', models.TextField(verbose_name='checkpoint storage id')),
                ('ml_id', models.IntegerField(verbose_name='ml id')),
                ('catalog_id', models.IntegerField(verbose_name='catalog id')),
                ('order', models.IntegerField(verbose_name='order')),
                ('config', models.TextField(verbose_name='config')),
                ('type', models.TextField(verbose_name='type')),
                ('version', models.TextField(verbose_name='version')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_marketplace', 'In Marketplace'), ('rented_bought', 'Rented/Bought'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend'), ('expired', 'Expired')], default='created', max_length=64, verbose_name='status')),
                ('file', models.FileField(null=True, upload_to='export')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetModelMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated at')),
                ('owner_id', models.IntegerField(verbose_name='owner id')),
                ('author_id', models.IntegerField(verbose_name='author id')),
                ('catalog_id', models.IntegerField(verbose_name='catalog id')),
                ('order', models.IntegerField(verbose_name='order')),
                ('config', models.TextField(verbose_name='config')),
                ('dataset_storage_id', models.IntegerField(verbose_name='dataset storage id')),
                ('type', models.TextField(null=True, verbose_name='type')),
                ('version', models.TextField(null=True, verbose_name='version')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_marketplace', 'In Marketplace'), ('rented_bought', 'Rented/Bought'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend'), ('expired', 'Expired')], default='created', max_length=64, null=True, verbose_name='status')),
                ('file', models.FileField(null=True, upload_to='export')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated at')),
                ('owner_id', models.IntegerField(verbose_name='owner id')),
                ('author_id', models.IntegerField(verbose_name='author id')),
                ('checkpoint_storage_id', models.TextField(verbose_name='checkpoint storage id')),
                ('ml_id', models.IntegerField(verbose_name='ml id')),
                ('catalog_id', models.IntegerField(verbose_name='catalog id')),
                ('order', models.IntegerField(verbose_name='order')),
                ('config', models.TextField(verbose_name='config')),
                ('dataset_storage_id', models.IntegerField(verbose_name='dataset storage id')),
                ('image_dockerhub_id', models.TextField(null=True, verbose_name='image dockerhub id')),
                ('infrastructure_id', models.TextField(null=True, verbose_name='infrastructure id')),
                ('model_desc', models.TextField(null=True, verbose_name='model_desc')),
                ('type', models.TextField(null=True, verbose_name='type')),
                ('ip_address', models.TextField(null=True, verbose_name='ip_address')),
                ('port', models.TextField(null=True, verbose_name='port')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_marketplace', 'In Marketplace'), ('rented_bought', 'Rented/Bought'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend'), ('expired', 'Expired')], default='created', max_length=64, null=True, verbose_name='status')),
                ('file', models.FileField(null=True, upload_to='export')),
            ],
        ),
        migrations.DeleteModel(
            name='checkpoint_model_marketplace',
        ),
        migrations.DeleteModel(
            name='dataset_model_marketplace',
        ),
        migrations.DeleteModel(
            name='model_marketplace',
        ),
    ]
