# Generated by Django 3.2.14 on 2024-02-01 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model_marketplace', '0002_auto_20240123_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadModelMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated at')),
                ('model_id', models.IntegerField(verbose_name='model id')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('ip_address', models.TextField(verbose_name='ip_address')),
                ('status', models.CharField(choices=[('actived', 'Actived'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend'), ('expired', 'Expired')], default='pending', max_length=64, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='LikeModelMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated at')),
                ('model_id', models.IntegerField(verbose_name='model id')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('ip_address', models.TextField(verbose_name='ip_address')),
                ('status', models.CharField(choices=[('actived', 'Actived'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend'), ('expired', 'Expired')], default='pending', max_length=64, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMarketplaceDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated at')),
                ('model_id', models.TextField(verbose_name='model_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
            ],
            options={
                'db_table': 'model_marketplace_download',
            },
        ),
        migrations.CreateModel(
            name='ModelMarketplaceLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated at')),
                ('model_id', models.TextField(verbose_name='model_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
            ],
            options={
                'db_table': 'model_marketplace_like',
            },
        ),
        migrations.AddField(
            model_name='modelmarketplace',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogmodelmarketplace',
            name='catalog_id',
            field=models.IntegerField(null=True, verbose_name='catalog id'),
        ),
        migrations.AlterField(
            model_name='catalogmodelmarketplace',
            name='order',
            field=models.IntegerField(default=0, null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='catalogmodelmarketplace',
            name='tag',
            field=models.TextField(null=True, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='catalogmodelmarketplace',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='modelmarketplace',
            name='catalog_id',
            field=models.IntegerField(default=0, verbose_name='catalog id'),
        ),
        migrations.AlterField(
            model_name='modelmarketplace',
            name='checkpoint_storage_id',
            field=models.TextField(default='', verbose_name='checkpoint storage id'),
        ),
        migrations.AlterField(
            model_name='modelmarketplace',
            name='config',
            field=models.TextField(default='', verbose_name='config'),
        ),
        migrations.AlterField(
            model_name='modelmarketplace',
            name='dataset_storage_id',
            field=models.IntegerField(default=0, verbose_name='dataset storage id'),
        ),
        migrations.AlterField(
            model_name='modelmarketplace',
            name='image_dockerhub_id',
            field=models.TextField(default='', null=True, verbose_name='image dockerhub id'),
        ),
        migrations.AlterField(
            model_name='modelmarketplace',
            name='ml_id',
            field=models.IntegerField(default=0, verbose_name='ml id'),
        ),
        migrations.AlterField(
            model_name='modelmarketplace',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterModelTable(
            name='catalogmodelmarketplace',
            table='catalog_model_marketplace',
        ),
    ]
