# Generated by Django 3.2.14 on 2024-03-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_marketplace', '0008_auto_20240226_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmarketplace',
            name='docker_access_token',
            field=models.TextField(null=True, verbose_name='docker_access_token'),
        ),
        migrations.AddField(
            model_name='modelmarketplace',
            name='docker_image',
            field=models.TextField(null=True, verbose_name='docker_image'),
        ),
    ]
