# Autogenerated by devscripts/update-version.py

__version__ = '2025.06.05.233116'

RELEASE_GIT_HEAD = '9e38b273b7ac942e7e9fc05a651ed810ab7d30ba'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.06.05.233116dev'
