import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_d893d7a7af(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_e1700027e1():spartaqube_cli.list()
@app.command()
def sparta_a995196964():spartaqube_cli.sparta_a995196964()
@app.command()
def sparta_0ea0a37377():print('Hello world!')
if __name__=='__main__':app()