TILE_ATTRIBUTES = {
    "sapling": ("grow",),
    "treeling": ("grow", "no_pickup"),
    "tree": ("no_pickup"),
    "spore": ("grow",),
    "mushroom": ("eat"),
    "carrot": ("grow", "eat"),
    "carroot": ("no_pickup"),
    "rabbit child": ("grow", "rabbit", "no_pickup"),
    "rabbit adult": ("rabbit", "no_pickup"),
    "roasted mushroom": ("eat",),
    "mushroom stew": ("eat",),
    "workbench": ("open", "craft"),
    "campfire": ("open", "craft", "light"),
    "sawbench": ("open", "craft", "multi"),
    "manual press": ("open", "craft", "multi"),
    "small crate": ("open", "store"),
    "small barrel": ("open", "store"),
    "wooden bed": ("sleep", "multi"),
    "rabbit meat": ("eat",),
    "roasted rabbit meat": ("eat",),
    "big rock": ("multi"),
    "mushroom shaper": ("open", "craft"),
    "coal ore": ("no_pickup"),
    "composter": ("open", "machine"),
    "bonsai pot": ("open", "machine", "multi"),
    # Special tiles
    "left": ("point", "no_pickup"),
    "up": ("point", "no_pickup"),
    "player": ("open", "craft", "no_pickup"),
    "junk": ("no_pickup",),
    "corpse": ("no_pickup",),
    "obelisk": ("multi", "no_pickup"),
}