# Generated by Django 3.2.14 on 2024-02-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute_marketplace', '0002_auto_20240123_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogComputeMarketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('catalog_id', models.IntegerField(null=True, verbose_name='catalog id')),
                ('order', models.IntegerField(default=0, null=True, verbose_name='order')),
                ('tag', models.TextField(null=True, verbose_name='tag')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_marketplace', 'In Marketplace'), ('rented_bought', 'Rented/Bought'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend'), ('expired', 'Expired')], default='created', max_length=64, null=True, verbose_name='status')),
                ('file', models.FileField(null=True, upload_to='export')),
            ],
            options={
                'db_table': 'catalog_compute_marketplace',
            },
        ),
        migrations.AddField(
            model_name='computemarketplace',
            name='card',
            field=models.IntegerField(null=True, verbose_name='card'),
        ),
        migrations.AddField(
            model_name='computemarketplace',
            name='price',
            field=models.FloatField(default=0, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='callback_url',
            field=models.TextField(default='', verbose_name='callback_url'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='catalog_id',
            field=models.IntegerField(default=0, verbose_name='catalog_id'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='config',
            field=models.TextField(default='', verbose_name='config'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='infrastructure_desc',
            field=models.TextField(default='', verbose_name='infrastructure_desc'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='name',
            field=models.TextField(default='', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='owner_id',
            field=models.IntegerField(verbose_name='owner_id'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='ssh_key',
            field=models.TextField(null=True, verbose_name='ssh_key'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='type',
            field=models.TextField(choices=[('MODEL-SYSTEM', 'MODEL-SYSTEM'), ('MODEL-CUSTOMER', 'MODEL-CUSTOMER')], default='MODEL-CUSTOMER', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='computemarketplace',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated at'),
        ),
        migrations.AlterModelTable(
            name='computemarketplace',
            table='compute_marketplace_compute_marketplace',
        ),
    ]
