# Generated by Django 3.2.14 on 2024-27-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compute_marketplace', '0027_add_field_history_rent_computes'),
    ]

    operations = [
        migrations.AddField(
            model_name="History_Rent_Computes",
            name="compute_install",
            field=models.CharField(choices=[ ('failed', 'Failed'), ('completed', 'Completed')], default='completed', max_length=50),
        ),
        
       
    ]
