# Generated by Django 3.2.14 on 2024-03-27 15:08

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ("compute_marketplace", "0037_auto_20240515_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="history_rent_computes",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("full", django.utils.translation.gettext_lazy("All Service")),
                    ("storage", django.utils.translation.gettext_lazy("Storage")),
                    (
                        "model_training",
                        django.utils.translation.gettext_lazy("Model Training"),
                    ),
                    (
                        "label_tool",
                        django.utils.translation.gettext_lazy("Labeling Tool"),
                    ),
                ],
                default="full",
                max_length=64,
                null=True,
                verbose_name=django.utils.translation.gettext_lazy("service_type"),
            ),
        ),
    ]
