# Generated by Django 3.2.14 on 2024-27-03 15:08

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ("compute_marketplace", "0038_add_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="computegpu",
            name="gpu_memory_used",
            field=models.TextField(
                _("gpu_memory_used convert to Bytes"), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="gpu_memory_bandwidth",
            field=models.TextField(
                _("gpu_memory_bandwidth convert to Bytes"), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="motherboard",
            field=models.TextField(_("motherboard"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="internet_up_speed",
            field=models.TextField(
                _("internet_up_speed convert to Mbps"), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="internet_down_speed",
            field=models.TextField(
                _("internet_down_speed convert to Mbps"), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="number_of_pcie_per_gpu",
            field=models.TextField(
                _("number_of_pcie_per_gpu ex:4.0,16x"), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="per_gpu_pcie_bandwidth",
            field=models.TextField(
                _("per_gpu_pcie_bandwidth convert to bytes"), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="eff_out_of_total_nu_of_cpu_virtual_cores",
            field=models.TextField(
                _("eff_out_of_total_nu_of_cpu_virtual_cores ex:42.7/128"),
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="eff_out_of_total_system_ram",
            field=models.TextField(
                _("eff_out_of_total_system_ram ex:86/258 convert to GB"),
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="max_cuda_version",
            field=models.TextField(_("max cuda version"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="driver_version",
            field=models.TextField(_("driver_version"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="reliability",
            field=models.FloatField(_("reliability"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="dl_performance_score",
            field=models.FloatField(_("dl_performance_score"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="dlp_score",
            field=models.FloatField(_("dlp_score"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="location_id",
            field=models.IntegerField(_("location_id"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="location_alpha2",
            field=models.TextField(_("location_alpha2 ex: vn"), blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="location_name",
            field=models.TextField(
                _("location_name ex: Viet Nam"), blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="computegpu",
            name="datacenter",
            field=models.TextField(
                _("datacenter, ex: datacenter/ miners/ consumerGpu"),
                blank=True,
                null=True,
            ),
        ),
    ]
