# Code generated by cnb.cool/cnb/sdk/cnb-sdk-generator. DO NOT EDIT.
# versions:
#    cnb-sdk-generator: 1.0.2
# source: https://api.cnb.cool/swagger.json

from pydantic import Field
from enum import Enum
from typing import Optional, Dict
from .models import CNBBaseModel

class SettingValue(Enum):
	DisableOrganizationReadme = 1
	CloudNativeDevOnly = 2
	UseRootGroupBranchProtectionOnly = 4
	ForbidRedefineBranchProtection = 8
	EnableTAPDAccess = 16
