__version__: str

def list_accounts(session, account_statuses: str) -> list: ...
def list_ou_accounts(session, ou_id: str) -> list: ...
def create_account_list(account_ids: str) -> list: ...
def get_credentials(session, assumed_role_arn: str, external_id: str) -> dict: ...
def test_function(account_id: str, items: dict) -> dict: ...
def main() -> None: ...
