from .datatype_definition import OWLDatatypeDefinition
from .declaration import OWLDeclaration
from .has_key import OWLHasKey
from .class_axiom import *
from .data_property_axiom import *
from .object_property_axiom import *
from .assertion import *
from .annotations import *
from .general import *