# Generated by Django 3.2.16 on 2023-07-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_taskqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskqueue',
            name='max_tries',
            field=models.IntegerField(default=10, verbose_name='max_tries'),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='status',
            field=models.TextField(default='', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='taskqueue',
            name='try_count',
            field=models.IntegerField(default=5, verbose_name='try_count'),
        ),
    ]
