from .grid import Grid2D as Grid2D, T as T
from .solver import Solver as Solver

def print_condensed(data: Grid2D[T]) -> None: ...
def print_csv(data: Grid2D[T]) -> None: ...
def print_arranged(data: Grid2D[T]) -> None: ...
def print_solution(solution: Solver, *, indent: str = ...) -> None: ...
