from typing import Any

def load(splitlines: bool = ..., splitrecords: Union[str, None] = ..., recordtype: Union[list[type], tuple[type, ...], type, None] = ..., *, lut: Union[dict[Union[str, None], Any], None] = ..., filename: Union[str, None] = ...) -> Union[list[Union[str, int, list[Union[str, int]]]], Any]: ...
def variant() -> Union[str, None]: ...
