from typing import Callable

__version__: str

def threads(function_name: Callable, iterators: list, items: dict, thread_num: int = 10) -> list: ...
def test_function(iterator, items) -> int: ...
def main() -> None: ...
