# Generated by Django 3.2.14 on 2024-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation_template', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='annotation_template',
        ),
        migrations.CreateModel(
            name='annotation_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated at')),
                ('author_id', models.IntegerField(verbose_name='author id')),
                ('order', models.IntegerField(verbose_name='order')),
                ('image', models.TextField(verbose_name='image')),
                ('details', models.TextField(verbose_name='ml details')),
                ('ml_image', models.TextField(verbose_name='ml_image')),
                ('ml_ip', models.IntegerField(verbose_name='ml_ip')),
                ('ml_port', models.IntegerField(verbose_name='ml_port')),
                ('config', models.TextField(blank=True, null=True, default='',verbose_name='config')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('infrastructure_id', models.TextField(blank=True, null=True, default='',verbose_name='infrastructure id')),
                ('data_type', models.TextField(blank=True, null=True, default='',verbose_name='data_type')),
            ],
        ),
    ]
