# Generated by Django 4.2 on 2025-04-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0008_alter_djbackuploglevel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djbackuplog',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='djbackuploglevel',
            options={},
        ),
    ]
