# Generated by Django 3.2.14 on 2024-02-26 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compute_marketplace', '0007_auto_20240226_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeGPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('infrastructure_id', models.TextField(verbose_name='infrastructure_id',  null=True )),
                ('gpu_name', models.TextField(verbose_name='gpu_name', null=True)),
                ('power_consumption', models.TextField(verbose_name='power_consumption', null=True  )),
                ('gpu_index', models.IntegerField(verbose_name='gpu_index', null=True)),
                ('gpu_memory', models.TextField(verbose_name='gpu_memory', null=True)),
                ('branch_name', models.TextField(verbose_name='branch_name', null=True)),
                ('gpu_id', models.TextField(max_length=10, verbose_name='gpu_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('pending', 'Pending'), ('suppend', 'Suppend')], default='created', max_length=64, null=True, verbose_name='status')),
            ],
            options={
                'db_table': 'compute_gpu',
            },
        ),
       
    ]
