# Generated by Django 3.2.14 on 2024-02-26 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compute_marketplace', '0008_auto_20240301_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeGpuPrice',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('compute_gpu_id', models.IntegerField(null=True)),
                ('token_symbol', models.TextField()),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'compute_gpu_price',
            },
        ),
       
    ]
