CHARACTER(256) :: fetxt(111)

   fetxt(1)=' Error opening'
   fetxt(2)=' End of File encountered'
   fetxt(3)=' Error reading'
   fetxt(4)=' Error writing'
   fetxt(5)=' Max. # nodes exceeded'
   fetxt(6)=' Max. # element types exceeded'
   fetxt(7)=' Max. bandwidth exceeded'
   fetxt(8)=' Max. # element nodes exceeded'
   fetxt(9)=' Max. # elements exceeded'
   fetxt(10)=' Max. # boundary elements exceeded'
   fetxt(11)=' Resistivity <= 0'
   fetxt(12)=' Max. # electrodes exceeded'
   fetxt(13)=' rwdanz > rwdmax'
   fetxt(14)=' Max. # measurements exceeded'
   fetxt(15)=' Inadmissible name of file'
   fetxt(16)=' panz > pmax'
   fetxt(17)=' stranz > strmax'
   fetxt(18)=' Inadmissible element type'
   fetxt(19)=' Bandwith of FE matrix exceeded'
   fetxt(20)=' Array subscript exceeded allocated area'
   fetxt(21)=' stranz > relmax'
   fetxt(22)=' Max. grade exceeded'
   fetxt(23)=' # init.nodes = 0'
   fetxt(24)=' Max. # init.nodes exceeded'
   fetxt(25)=' # init.nodes > # nodes'
   fetxt(26)=' Determinant of FE matrix <= 0'
   fetxt(27)=' FE matrix element <= 0'
   fetxt(28)=' FE matrix indefinite'
   fetxt(29)=' Electrode node > # nodes'
   fetxt(30)=' rwdnr(i) > sanz'
   fetxt(31)=' Init.node > # nodes'
   fetxt(32)=' Max. # wavenumbers exceeded'
   fetxt(33)=' rwnanz > relmax'
   fetxt(34)=' Execution time :'
   fetxt(35)=' Error during calculation of boundary elements. Check electrode positions.'
   fetxt(36)=' Array subscript exceeded allocated area'
   fetxt(37)=' Wavenumber <= 0'
   fetxt(38)=' Error during back transformation. Check wavenumbers.'
   fetxt(39)=' Resistivity = 0'
   fetxt(40)=' Wavenumber too small'
   fetxt(41)=' Wavenumber too large'
   fetxt(42)=' Max. # model parameters exceeded'
   fetxt(43)=' Error during back transformation. Check wavenumbers.'
   fetxt(44)=' Error during back transformation. Check wavenumbers.'
   fetxt(45)=' Error in rtrafm'
   fetxt(46)=' Inadmissible electrode denotation'
   fetxt(47)=' # elements inconsistent'
   fetxt(48)=' Inadmissible electrode denotation'
   fetxt(49)=' Max. # measurements exceeded'
   fetxt(50)=' # model parameters and # elements inconsistent'
   fetxt(51)=' Max. # model parameters exceeded'
   fetxt(52)=' kanz > sanz'
   fetxt(53)=' knr > sanz'
   fetxt(54)=' Electrode > # electrodes'
   fetxt(55)=' sensj = 0'
   fetxt(56)=' sensi = 0'
   fetxt(57)=' Inadmissible noise level'
   fetxt(58)=' Inadmissible type of reconstruction'
   fetxt(59)=' Relaxation parameter lambda < 1'
   fetxt(60)=' Inadmissible index of 1st iteration'
   fetxt(61)=' Inadmissible max. # iterations'
   fetxt(62)=' Min. data RMS < 1e-12'
   fetxt(63)=' Max. # model parameters exceeded'
   fetxt(64)=' Inadmissible min. rel. decrease of data RMS'
   fetxt(65)=' Inadmissible resistivity constraints'
   fetxt(66)=' Inadmissible filter window'
   fetxt(67)=' Inadmissible parameter alpha'
   fetxt(68)=' Inadmissible filter repetition'
   fetxt(69)=' nx, nz inconsistent'
   fetxt(70)=' # model parameters, # elements inconsistent'
   fetxt(71)=' Min. voltage vmin < 0'
   fetxt(72)=' # wavenumbers < 5'
   fetxt(73)=' Distance between electrodes <= 0'
   fetxt(74)=' Distance between electrode and boundary <= 0'
   fetxt(75)=' nanz > (mbmax+1)*smax'
   fetxt(76)=' manz > smax*emax'
   fetxt(77)=' Damping parameter nmin >= 0'
   fetxt(78)=' Increasing RMS. Execution time:'
   fetxt(79)=' Max. # iterations. Execution time:'
   fetxt(80)=' Min. RMS . Execution time:'
   fetxt(81)=' Min. rel. RMS decrease . Execution time:'
   fetxt(82)=' Modelled voltage = 0'
   fetxt(83)=' Inadmissible max. # relaxation iterations'
   fetxt(84)=' Inadmissible min. CG error'
   fetxt(85)=' Inadmissible regularisation parameters'
   fetxt(86)=' Inadmissible Fourier transformation'
   fetxt(87)=' Negative polarity'
   fetxt(88)=' Standard deviation <= 0'
   fetxt(89)=' nx < 2 or nz < 2'
   fetxt(90)=' Min. L1 norm < 1'
   fetxt(91)=' Inadmissible background resistivity'
   fetxt(92)=' Min. step-length for 2nd time'
   fetxt(93)=' Infinite geometrical factor'
   fetxt(94)=' Magnitude <= 0'
   fetxt(95)=' Phase > pi'
   fetxt(96)=' Inadmissible smoothing parameter'
   fetxt(97)=' Out of memory'
   fetxt(98)=' Inadmissible step factor'
   fetxt(99)=' All data excluded'
   fetxt(100)=' Specify starting model'
   fetxt(101)=' Combined usage of homogeneous Dirichlet and mixed boundary condition unallowed'
   fetxt(102)=' Specify fictitious sink node'
   fetxt(103)=' Specify Dirichtlet node'
   fetxt(104)=' Invalid parameters in resistance error model'
   fetxt(105)=' Invalid parameters in phase error model'
   fetxt(106)=' Mixed boundary condition not implemented for pure 2D'
   fetxt(107)=' Cholesky decomposition failed factorization'
   fetxt(108)=' Solving linear system failed indefinite?'
   fetxt(109)=' Min. stepsize reached Execution time:'
   fetxt(110)=' Mixed boundary condition not yet implemented for 2D case'
