data1 = {
  "/diagnostics": "diagnostic_msgs/msg/DiagnosticArray",
  "/drone0/mavros/actuator_control": "mavros_msgs/msg/ActuatorControl",
  "/drone0/mavros/adsb/send": "mavros_msgs/msg/ADSBVehicle",
  "/drone0/mavros/adsb/vehicle": "mavros_msgs/msg/ADSBVehicle",
  "/drone0/mavros/altitude": "mavros_msgs/msg/Altitude",
  "/drone0/mavros/battery": "sensor_msgs/msg/BatteryState",
  "/drone0/mavros/cam_imu_sync/cam_imu_stamp": "mavros_msgs/msg/CamIMUStamp",
  "/drone0/mavros/camera/image_captured": "mavros_msgs/msg/CameraImageCaptured",
  "/drone0/mavros/cellular_status/status": "mavros_msgs/msg/CellularStatus",
  "/drone0/mavros/companion_process/status":
    "mavros_msgs/msg/CompanionProcessStatus",
  "/drone0/mavros/debug_value/debug": "mavros_msgs/msg/DebugValue",
  "/drone0/mavros/debug_value/debug_float_array": "mavros_msgs/msg/DebugValue",
  "/drone0/mavros/debug_value/debug_vector": "mavros_msgs/msg/DebugValue",
  "/drone0/mavros/debug_value/named_value_float": "mavros_msgs/msg/DebugValue",
  "/drone0/mavros/debug_value/named_value_int": "mavros_msgs/msg/DebugValue",
  "/drone0/mavros/debug_value/send": "mavros_msgs/msg/DebugValue",
  "/drone0/mavros/esc_status/info": "mavros_msgs/msg/ESCInfo",
  "/drone0/mavros/esc_status/status": "mavros_msgs/msg/ESCStatus",
  "/drone0/mavros/esc_telemetry/telemetry": "mavros_msgs/msg/ESCTelemetry",
  "/drone0/mavros/estimator_status": "mavros_msgs/msg/EstimatorStatus",
  "/drone0/mavros/extended_state": "mavros_msgs/msg/ExtendedState",
  "/drone0/mavros/fake_gps/mocap/pose": "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/geofence/fences": "mavros_msgs/msg/WaypointList",
  "/drone0/mavros/gimbal_control/device/attitude_status":
    "mavros_msgs/msg/GimbalDeviceAttitudeStatus",
  "/drone0/mavros/gimbal_control/device/info":
    "mavros_msgs/msg/GimbalDeviceInformation",
  "/drone0/mavros/gimbal_control/device/set_attitude":
    "mavros_msgs/msg/GimbalDeviceSetAttitude",
  "/drone0/mavros/gimbal_control/manager/info":
    "mavros_msgs/msg/GimbalManagerInformation",
  "/drone0/mavros/gimbal_control/manager/set_attitude":
    "mavros_msgs/msg/GimbalManagerSetAttitude",
  "/drone0/mavros/gimbal_control/manager/set_manual_control":
    "mavros_msgs/msg/GimbalManagerSetPitchyaw",
  "/drone0/mavros/gimbal_control/manager/set_pitchyaw":
    "mavros_msgs/msg/GimbalManagerSetPitchyaw",
  "/drone0/mavros/gimbal_control/manager/status":
    "mavros_msgs/msg/GimbalManagerStatus",
  "/drone0/mavros/global_position/compass_hdg": "std_msgs/msg/Float64",
  "/drone0/mavros/global_position/global": "sensor_msgs/msg/NavSatFix",
  "/drone0/mavros/global_position/gp_lp_offset":
    "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/global_position/gp_origin":
    "geographic_msgs/msg/GeoPointStamped",
  "/drone0/mavros/global_position/local": "nav_msgs/msg/Odometry",
  "/drone0/mavros/global_position/raw/fix": "sensor_msgs/msg/NavSatFix",
  "/drone0/mavros/global_position/raw/gps_vel":
    "geometry_msgs/msg/TwistStamped",
  "/drone0/mavros/global_position/raw/satellites": "std_msgs/msg/UInt32",
  "/drone0/mavros/global_position/rel_alt": "std_msgs/msg/Float64",
  "/drone0/mavros/global_position/set_gp_origin":
    "geographic_msgs/msg/GeoPointStamped",
  "/drone0/mavros/gps_input/gps_input": "mavros_msgs/msg/GPSINPUT",
  "/drone0/mavros/gps_rtk/rtk_baseline": "mavros_msgs/msg/RTKBaseline",
  "/drone0/mavros/gps_rtk/send_rtcm": "mavros_msgs/msg/RTCM",
  "/drone0/mavros/gpsstatus/gps1/raw": "mavros_msgs/msg/GPSRAW",
  "/drone0/mavros/gpsstatus/gps1/rtk": "mavros_msgs/msg/GPSRTK",
  "/drone0/mavros/gpsstatus/gps2/raw": "mavros_msgs/msg/GPSRAW",
  "/drone0/mavros/gpsstatus/gps2/rtk": "mavros_msgs/msg/GPSRTK",
  "/drone0/mavros/hil/actuator_controls": "mavros_msgs/msg/HilActuatorControls",
  "/drone0/mavros/hil/controls": "mavros_msgs/msg/HilControls",
  "/drone0/mavros/hil/gps": "mavros_msgs/msg/HilGPS",
  "/drone0/mavros/hil/imu_ned": "mavros_msgs/msg/HilSensor",
  "/drone0/mavros/hil/optical_flow": "mavros_msgs/msg/OpticalFlowRad",
  "/drone0/mavros/hil/rc_inputs": "mavros_msgs/msg/RCIn",
  "/drone0/mavros/hil/state": "mavros_msgs/msg/HilStateQuaternion",
  "/drone0/mavros/home_position/home": "mavros_msgs/msg/HomePosition",
  "/drone0/mavros/home_position/set": "mavros_msgs/msg/HomePosition",
  "/drone0/mavros/imu/data": "sensor_msgs/msg/Imu",
  "/drone0/mavros/imu/data_raw": "sensor_msgs/msg/Imu",
  "/drone0/mavros/imu/diff_pressure": "sensor_msgs/msg/FluidPressure",
  "/drone0/mavros/imu/mag": "sensor_msgs/msg/MagneticField",
  "/drone0/mavros/imu/static_pressure": "sensor_msgs/msg/FluidPressure",
  "/drone0/mavros/imu/temperature_baro": "sensor_msgs/msg/Temperature",
  "/drone0/mavros/imu/temperature_imu": "sensor_msgs/msg/Temperature",
  "/drone0/mavros/landing_target/lt_marker": "geometry_msgs/msg/Vector3Stamped",
  "/drone0/mavros/landing_target/pose": "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/landing_target/pose_in": "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/local_position/accel":
    "geometry_msgs/msg/AccelWithCovarianceStamped",
  "/drone0/mavros/local_position/odom": "nav_msgs/msg/Odometry",
  "/drone0/mavros/local_position/pose": "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/local_position/pose_cov":
    "geometry_msgs/msg/PoseWithCovarianceStamped",
  "/drone0/mavros/local_position/velocity_body":
    "geometry_msgs/msg/TwistStamped",
  "/drone0/mavros/local_position/velocity_body_cov":
    "geometry_msgs/msg/TwistWithCovarianceStamped",
  "/drone0/mavros/local_position/velocity_local":
    "geometry_msgs/msg/TwistStamped",
  "/drone0/mavros/log_transfer/raw/log_data": "mavros_msgs/msg/LogData",
  "/drone0/mavros/log_transfer/raw/log_entry": "mavros_msgs/msg/LogEntry",
  "/drone0/mavros/mag_calibration/report":
    "mavros_msgs/msg/MagnetometerReporter",
  "/drone0/mavros/mag_calibration/status": "std_msgs/msg/UInt8",
  "/drone0/mavros/manual_control/control": "mavros_msgs/msg/ManualControl",
  "/drone0/mavros/manual_control/send": "mavros_msgs/msg/ManualControl",
  "/drone0/mavros/mission/reached": "mavros_msgs/msg/WaypointReached",
  "/drone0/mavros/mission/waypoints": "mavros_msgs/msg/WaypointList",
  "/drone0/mavros/mocap/pose": "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/mocap/tf": "geometry_msgs/msg/TransformStamped",
  "/drone0/mavros/mount_control/command": "mavros_msgs/msg/MountControl",
  "/drone0/mavros/mount_control/orientation": "geometry_msgs/msg/Quaternion",
  "/drone0/mavros/mount_control/status": "geometry_msgs/msg/Vector3Stamped",
  "/drone0/mavros/nav_controller_output/output":
    "mavros_msgs/msg/NavControllerOutput",
  "/drone0/mavros/obstacle/send": "sensor_msgs/msg/LaserScan",
  "/drone0/mavros/odometry/in": "nav_msgs/msg/Odometry",
  "/drone0/mavros/odometry/out": "nav_msgs/msg/Odometry",
  "/drone0/mavros/onboard_computer/status":
    "mavros_msgs/msg/OnboardComputerStatus",
  "/drone0/mavros/optical_flow/ground_distance": "sensor_msgs/msg/Range",
  "/drone0/mavros/optical_flow/raw/optical_flow": "mavros_msgs/msg/OpticalFlow",
  "/drone0/mavros/optical_flow/raw/send": "mavros_msgs/msg/OpticalFlow",
  "/drone0/mavros/param/event": "mavros_msgs/msg/ParamEvent",
  "/drone0/mavros/play_tune": "mavros_msgs/msg/PlayTuneV2",
  "/drone0/mavros/px4flow/ground_distance": "sensor_msgs/msg/Range",
  "/drone0/mavros/px4flow/raw/optical_flow_rad":
    "mavros_msgs/msg/OpticalFlowRad",
  "/drone0/mavros/px4flow/raw/send": "mavros_msgs/msg/OpticalFlowRad",
  "/drone0/mavros/px4flow/temperature": "sensor_msgs/msg/Temperature",
  "/drone0/mavros/radio_status": "mavros_msgs/msg/RadioStatus",
  "/drone0/mavros/rallypoint/rallypoints": "mavros_msgs/msg/WaypointList",
  "/drone0/mavros/rangefinder/rangefinder": "sensor_msgs/msg/Range",
  "/drone0/mavros/rangefinder_pub": "sensor_msgs/msg/Range",
  "/drone0/mavros/rangefinder_sub": "sensor_msgs/msg/Range",
  "/drone0/mavros/rc/in": "mavros_msgs/msg/RCIn",
  "/drone0/mavros/rc/out": "mavros_msgs/msg/RCOut",
  "/drone0/mavros/setpoint_raw/target_attitude":
    "mavros_msgs/msg/AttitudeTarget",
  "/drone0/mavros/setpoint_raw/target_global":
    "mavros_msgs/msg/GlobalPositionTarget",
  "/drone0/mavros/setpoint_raw/target_local": "mavros_msgs/msg/PositionTarget",
  "/drone0/mavros/setpoint_trajectory/desired": "nav_msgs/msg/Path",
  "/drone0/mavros/state": "mavros_msgs/msg/State",
  "/drone0/mavros/status_event": "mavros_msgs/msg/StatusEvent",
  "/drone0/mavros/statustext/recv": "mavros_msgs/msg/StatusText",
  "/drone0/mavros/sys_status": "mavros_msgs/msg/SysStatus",
  "/drone0/mavros/target_actuator_control": "mavros_msgs/msg/ActuatorControl",
  "/drone0/mavros/terrain/report": "mavros_msgs/msg/TerrainReport",
  "/drone0/mavros/time_reference": "sensor_msgs/msg/TimeReference",
  "/drone0/mavros/timesync_status": "mavros_msgs/msg/TimesyncStatus",
  "/drone0/mavros/trajectory/desired": "mavros_msgs/msg/Trajectory",
  "/drone0/mavros/tunnel/out": "mavros_msgs/msg/Tunnel",
  "/drone0/mavros/vfr_hud": "mavros_msgs/msg/VfrHud",
  "/drone0/mavros/vibration/raw/vibration": "mavros_msgs/msg/Vibration",
  "/drone0/mavros/wheel_odometry/distance": "mavros_msgs/msg/WheelOdomStamped",
  "/drone0/mavros/wheel_odometry/odom": "nav_msgs/msg/Odometry",
  "/drone0/mavros/wheel_odometry/rpm": "mavros_msgs/msg/WheelOdomStamped",
  "/drone0/mavros/wind_estimation":
    "geometry_msgs/msg/TwistWithCovarianceStamped",
  "/mission_status_topic": "vyom_mission_msgs/msg/MissionStatus",
  "/move_base_simple/goal": "geometry_msgs/msg/PoseStamped",
  "/parameter_events": "rcl_interfaces/msg/ParameterEvent",
  "/rosout": "rcl_interfaces/msg/Log",
  "/tf": "tf2_msgs/msg/TFMessage",
  "/tf_static": "tf2_msgs/msg/TFMessage",
  "/uas1/mavlink_sink": "mavros_msgs/msg/Mavlink",
  "/uas1/mavlink_source": "mavros_msgs/msg/Mavlink",
};

data2 = {
  "/Navigate/_action/feedback":
    "vyom_mission_msgs/action/DroneNavigation_FeedbackMessage",
  "/Navigate/_action/status": "action_msgs/msg/GoalStatusArray",
  "/SendData/_action/feedback":
    "vyom_mission_msgs/action/DynamicSubscriber_FeedbackMessage",
  "/SendData/_action/status": "action_msgs/msg/GoalStatusArray",
  "/Takeoff/_action/feedback":
    "vyom_mission_msgs/action/Takeoff_FeedbackMessage",
  "/Takeoff/_action/status": "action_msgs/msg/GoalStatusArray",
  "/airsim/pointcloud": "sensor_msgs/msg/PointCloud2",
  "/behavior_tree_node/transition_event": "lifecycle_msgs/msg/TransitionEvent",
  "/camera/color/image_raw": "sensor_msgs/msg/Image",
  "/camera_down/down_cam/image_raw": "sensor_msgs/msg/Image",
  "/diagnostics": "diagnostic_msgs/msg/DiagnosticArray",
  "/drone0/mavros/battery": "sensor_msgs/msg/BatteryState",
  "/drone0/mavros/global_position/global": "sensor_msgs/msg/NavSatFix",
  "/drone0/mavros/global_position/rel_alt": "std_msgs/msg/Float64",
  "/drone0/mavros/local_position/pose": "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/local_position/velocity_body":
    "geometry_msgs/msg/TwistStamped",
  "/drone0/mavros/setpoint_position/local": "geometry_msgs/msg/PoseStamped",
  "/drone0/mavros/setpoint_velocity/cmd_vel": "geometry_msgs/msg/Twist",
  "/drone0/mavros/state": "mavros_msgs/msg/State",
  "/mission_status_topic": "vyom_mission_msgs/msg/MissionStatus",
  "/parameter_events": "rcl_interfaces/msg/ParameterEvent",
  "/rosout": "rcl_interfaces/msg/Log",
  "/tf_static": "tf2_msgs/msg/TFMessage",
  "/uas1/mavlink_source": "mavros_msgs/msg/Mavlink",
};


topic_list - {"/drone0/mavros/setpoint_position/local": "geometry_msgs/msg/PoseStamped",
"/drone0/mavros/setpoint_velocity/cmd_vel": "geometry_msgs/msg/Twist",
"/drone0/mavros/state": "mavros_msgs/msg/State",
"/mission_status_topic": "vyom_mission_msgs/msg/MissionStatus",
"/parameter_events": "rcl_interfaces/msg/ParameterEvent",
"/rosout": "rcl_interfaces/msg/Log",
"/tf_static": "tf2_msgs/msg/TFMessage",
"/uas1/mavlink_source": "mavros_msgs/msg/Mavlink",
};