from enum import Enum


class SherpaJobBeanType(str, Enum):
    ADD_CATEGORY = "ADD_CATEGORY"
    ADD_METADATA = "ADD_METADATA"
    BACKUP_USER_SESSION = "BACKUP_USER_SESSION"
    CORPUS_ANNOTATE = "CORPUS_ANNOTATE"
    DELETE_DOCS = "DELETE_DOCS"
    DELETE_LABELLING = "DELETE_LABELLING"
    DELETE_LABELS = "DELETE_LABELS"
    DOC_IMPORT = "DOC_IMPORT"
    EXPERIMENT_TRAINING = "EXPERIMENT_TRAINING"
    PROCESS_CANDIDATES = "PROCESS_CANDIDATES"
    PROJECTS_INDEXING = "PROJECTS_INDEXING"
    PROJECT_INDEXING = "PROJECT_INDEXING"
    PROJECT_RESTORATION = "PROJECT_RESTORATION"
    PROJECT_SEGMENTATION = "PROJECT_SEGMENTATION"
    PROJECT_VECTORIZATION = "PROJECT_VECTORIZATION"
    SPLIT_CORPUS = "SPLIT_CORPUS"
    SYNCHRONIZE_TERMS = "SYNCHRONIZE_TERMS"
    TERM_IMPORT = "TERM_IMPORT"
    TRAIN_AND_SUGGEST = "TRAIN_AND_SUGGEST"
    UNSPECIFIED = "UNSPECIFIED"

    def __str__(self) -> str:
        return str(self.value)
