# Generated by Django 5.0.7 on 2024-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0016_lessonevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonevent',
            name='slot_number_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End slot number'),
        ),
        migrations.AddField(
            model_name='lessonevent',
            name='slot_number_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Start slot number'),
        ),
    ]
