# Generated by Django 5.0.7 on 2024-08-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0022_add_substitution_global_permission'),
        ('core', '0069_add_calendar_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEventAlarm',
            fields=[
                ('calendaralarm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.calendaralarm')),
                ('status', models.CharField(choices=[('C', 'Created'), ('E', 'Edited'), ('D', 'Deleted')], default='C', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Lesson event alarm',
                'verbose_name_plural': 'Lesson event alarms',
            },
            bases=('core.calendaralarm',),
        ),
    ]
