# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk.api.notifications_admin_api import NotificationsAdminApi


class TestNotificationsAdminApi(unittest.TestCase):
    """NotificationsAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsAdminApi()

    def tearDown(self) -> None:
        pass

    def test_create_notification(self) -> None:
        """Test case for create_notification

        """
        pass

    def test_get_notification_template_admin(self) -> None:
        """Test case for get_notification_template_admin

        """
        pass

    def test_send_test_email_admin(self) -> None:
        """Test case for send_test_email_admin

        """
        pass


if __name__ == '__main__':
    unittest.main()
