# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk.models.session_create_response_dto import SessionCreateResponseDto

class TestSessionCreateResponseDto(unittest.TestCase):
    """SessionCreateResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionCreateResponseDto:
        """Test SessionCreateResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionCreateResponseDto`
        """
        model = SessionCreateResponseDto()
        if include_optional:
            return SessionCreateResponseDto(
                created_at = '',
                current = True,
                device_os = '',
                device_type = '',
                expires_at = '',
                id = '',
                token = '',
                updated_at = ''
            )
        else:
            return SessionCreateResponseDto(
                created_at = '',
                current = True,
                device_os = '',
                device_type = '',
                id = '',
                token = '',
                updated_at = '',
        )
        """

    def testSessionCreateResponseDto(self):
        """Test SessionCreateResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
