# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_notification(self) -> None:
        """Test case for delete_notification

        """
        pass

    def test_delete_notifications(self) -> None:
        """Test case for delete_notifications

        """
        pass

    def test_get_notification(self) -> None:
        """Test case for get_notification

        """
        pass

    def test_get_notifications(self) -> None:
        """Test case for get_notifications

        """
        pass

    def test_update_notification(self) -> None:
        """Test case for update_notification

        """
        pass

    def test_update_notifications(self) -> None:
        """Test case for update_notifications

        """
        pass


if __name__ == '__main__':
    unittest.main()
