# Generated by Django 3.2.14 on 2024-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('actived', 'Actived'), ('pending', 'Pending'), ('suppend', 'Suppend')], default='pending', max_length=64, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, help_text='is admin of Organization', verbose_name='is_admin'),
        ),
    ]
