# Generated by Django 3.2.14 on 2023-02-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_control_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batch_size',
            field=models.IntegerField(default=8, help_text='Batch size', verbose_name='batch size'),
        ),
        migrations.AddField(
            model_name='project',
            name='epochs',
            field=models.IntegerField(default=10, help_text='Number of epochs', verbose_name='number of epochs'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_height',
            field=models.IntegerField(default=320, help_text='Image height', verbose_name='image height'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_width',
            field=models.IntegerField(default=320, help_text='Image width', verbose_name='image width'),
        ),
    ]
