# Generated by Django 3.2.16 on 2023-07-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='audio_approved_mono_duration',
            field=models.FloatField(default=0, help_text='Total duration of approved mono audio files', verbose_name='audio duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='audio_approved_stereo_duration',
            field=models.FloatField(default=0, help_text='Total duration of approved stereo audio files', verbose_name='audio duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='audio_mono_duration',
            field=models.FloatField(default=0, help_text='Total duration of mono audio files', verbose_name='audio duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='audio_rejected_mono_duration',
            field=models.FloatField(default=0, help_text='Total duration of rejected mono audio files', verbose_name='audio duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='audio_rejected_stereo_duration',
            field=models.FloatField(default=0, help_text='Total duration of rejected stereo audio files', verbose_name='audio duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='audio_stereo_duration',
            field=models.FloatField(default=0, help_text='Total duration of stereo audio files', verbose_name='audio duration'),
        ),
    ]
