# Generated by Django 3.2.14 on 2023-07-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20230727_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotations_limit',
            field=models.IntegerField(default=None, help_text='Maximum annotations number per task', null=True, verbose_name='annotations limit'),
        ),
    ]
