# Generated by Django 3.2.14 on 2023-10-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20231017_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='need_to_qa',
            field=models.BooleanField(default=False, help_text='Whether or not the project is needed to review tasks', verbose_name='need to QA'),
        ),
    ]
