# Generated by Django 3.2.14 on 2024-03-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_add_field_project'),
    ]

    operations = [
      migrations.RemoveField(
            model_name='project',
            name='accuracy',
            field=models.FloatField(('accuracy'),  help_text='accuracy', null=True, blank=True)
        ),
        migrations.RemoveField(
            model_name='project',
            name='precision',
            field=models.TextField(('precision'),  help_text='precision', null=True, blank=True)
        ),
    ]
