# Generated by Django 3.2.14 on 2023-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_allow_newsletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_qa',
            field=models.BooleanField(default=False, help_text='Designates whether the user can review tasks.', verbose_name='is QA'),
        ),
    ]
