# Generated by Django 3.2.14 on 2023-11-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20231031_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
                ('link', models.CharField(max_length=256, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
