# coding: utf-8

"""
    eLabFTW REST API v2 Documentation

    This document describes all available endpoints and methods for eLabFTW's API version 2. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from elabapi_python.api.items_types_api import ItemsTypesApi


class TestItemsTypesApi(unittest.TestCase):
    """ItemsTypesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsTypesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_items_type(self) -> None:
        """Test case for delete_items_type

        Delete a resource category.
        """
        pass

    def test_get_items_type(self) -> None:
        """Test case for get_items_type

        Read a resource category.
        """
        pass

    def test_patch_items_type(self) -> None:
        """Test case for patch_items_type

        Modify a resource category.
        """
        pass

    def test_post_items_types(self) -> None:
        """Test case for post_items_types

        Create a resource category
        """
        pass

    def test_read_items_types(self) -> None:
        """Test case for read_items_types

        Read all resources categories that are accessible.
        """
        pass


if __name__ == '__main__':
    unittest.main()
