# coding: utf-8

"""
    eLabFTW REST API v2 Documentation

    This document describes all available endpoints and methods for eLabFTW's API version 2. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from elabapi_python.api.teamgroups_api import TeamgroupsApi


class TestTeamgroupsApi(unittest.TestCase):
    """TeamgroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamgroupsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_teamgroup(self) -> None:
        """Test case for delete_teamgroup

        Delete a teamgroup.
        """
        pass

    def test_patch_teamgroup(self) -> None:
        """Test case for patch_teamgroup

        Modify a teamgroup.
        """
        pass

    def test_post_teamgroups(self) -> None:
        """Test case for post_teamgroups

        Create a new teamgroup.
        """
        pass

    def test_read_team_teamgroups(self) -> None:
        """Test case for read_team_teamgroups

        Read teamgroups of a team.
        """
        pass

    def test_read_teamgroup(self) -> None:
        """Test case for read_teamgroup

        Read a teamgroup.
        """
        pass


if __name__ == '__main__':
    unittest.main()
