# coding: utf-8

"""
    eLabFTW REST API v2 Documentation

    This document describes all available endpoints and methods for eLabFTW's API version 2. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from elabapi_python.models.read_teamgroup200_response import ReadTeamgroup200Response

class TestReadTeamgroup200Response(unittest.TestCase):
    """ReadTeamgroup200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadTeamgroup200Response:
        """Test ReadTeamgroup200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadTeamgroup200Response`
        """
        model = ReadTeamgroup200Response()
        if include_optional:
            return ReadTeamgroup200Response(
                id = 56,
                name = '',
                team = 56
            )
        else:
            return ReadTeamgroup200Response(
        )
        """

    def testReadTeamgroup200Response(self):
        """Test ReadTeamgroup200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
