# Generated by Django 3.2.14 on 2024-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_alter_mlgpu_infrastructure_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLBackendStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.IntegerField(default=0, verbose_name='ml_id')),
                ('project_id', models.IntegerField(default=0, verbose_name='project_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('worker', 'Worker'), ('master', 'Master'), ('join_master', 'Join_master'), ('reject_master', 'Reject_master'), ('training', 'Training'), ('stop', 'Stop'), ('finish', 'Finish')], default='worker', max_length=64, null=True, verbose_name='status')),
                ('status_training', models.CharField(choices=[('worker', 'Worker'), ('master', 'Master'), ('join_master', 'Join_master'), ('reject_master', 'Reject_master'), ('training', 'Training'), ('stop', 'Stop'), ('finish', 'Finish')], default='join_master', max_length=64, null=True, verbose_name='status')),
                ('status_stop', models.CharField(choices=[('worker', 'Worker'), ('master', 'Master'), ('join_master', 'Join_master'), ('reject_master', 'Reject_master'), ('training', 'Training'), ('stop', 'Stop'), ('finish', 'Finish')], default='reject_master', max_length=64, null=True, verbose_name='status')),
            ],
        ),
    ]