# Generated by Django 4.2 on 2025-04-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0003_remove_djstorage_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJStoragePickle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
