# Generated by Django 4.2 on 2025-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_backup', '0006_djbackuplogemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJBackupLogLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_n', models.IntegerField(default=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DJBackupLogEmail',
        ),
        migrations.RemoveField(
            model_name='djbackuplog',
            name='name',
        ),
        migrations.AddField(
            model_name='djbackuplog',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djbackuplog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='djbackuplog',
            name='exc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
